#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9*
rm -rf constant/polyMesh

#------------------------------------------------------------------------------
