#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch current.foam
runApplication blockMesh
#cp 0/T_template 0/T
cp 0/ph_rgh_template 0/ph_rgh
#funkySetFields -field T -expression "sqrt(sqr(pos().x - 0)/sqr(4000) + sqr(pos().y - 3000)/sqr(2000))<=1 ? 300 - 9.81*pos().y/1000 -7.5*(1 + cos(3.14*(sqrt(sqr(pos().x -0)/sqr(4000) + sqr(pos().y - 3000)/sqr(2000))))) : 300 - 9.81*pos().y/1000" -time 0
#funkySetFields -field theta -expression "sqrt(sqr(pos().x - 0)/sqr(4000) + sqr(pos().y - 3000)/sqr(2000))<=1 ? 300 -7.5*(1 + cos(3.14*(sqrt(sqr(pos().x -0)/sqr(4000) + sqr(pos().y - 3000)/sqr(2000))))) : 300" -time 0
#funkySetFields -field theta0 -expression "300" -time 0


#runApplication StrakaFoam


./../../../src/StrakaFoam_HB_pot/StrakaFoam_HB_pot



#------------------------------------------------------------------------------
