#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp 0/ph_rgh_template 0/ph_rgh
runApplication $(getApplication)





#------------------------------------------------------------------------------
