#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh
rm -rf 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9*
rm log*
rm *.foam



#------------------------------------------------------------------------------
